# Generated by Django 3.0.9 on 2020-08-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_diary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
