# Generated by Django 3.0.9 on 2020-08-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='user_profile',
        ),
    ]
